# Generated by Django 3.2.8 on 2021-10-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('staff', '0002_auto_20211001_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=None, max_length=64, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name_kana',
            field=models.CharField(default=None, max_length=64, verbose_name='なまえ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=None, max_length=64, verbose_name='苗字'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name_kana',
            field=models.CharField(default=None, max_length=64, verbose_name='みょうじ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], default=None, max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.job', verbose_name='職種名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.role', verbose_name='権限名'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
