# Generated by Django 3.2.8 on 2021-10-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20211008_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clerk',
            options={'verbose_name': '事務員', 'verbose_name_plural': '6.事務員'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '医師', 'verbose_name_plural': '1.医師'},
        ),
        migrations.AlterModelOptions(
            name='nurse',
            options={'verbose_name': '看護師', 'verbose_name_plural': '2.看護師'},
        ),
        migrations.AlterModelOptions(
            name='occupational',
            options={'verbose_name': '作業療法士', 'verbose_name_plural': '5.作業療法士'},
        ),
        migrations.AlterModelOptions(
            name='pharmacist',
            options={'verbose_name': '薬剤師', 'verbose_name_plural': '3.薬剤師'},
        ),
        migrations.AlterModelOptions(
            name='physical',
            options={'verbose_name': '理学療法士', 'verbose_name_plural': '4.理学療法士'},
        ),
    ]
