# Generated by Django 3.2.8 on 2021-10-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20211008_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerk',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='occupational',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='physical',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], max_length=8, verbose_name='性別'),
        ),
    ]
