# Generated by Django 3.2.8 on 2021-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='target',
            field=models.CharField(choices=[('DOCTOR', '医師'), ('NURSE', '看護師'), ('PHARMACIST', '薬剤師'), ('PHYSICAL', '理学療法士'), ('OCCUPATIONAL', '作業療法士'), ('CLERK', '事務員')], max_length=32, verbose_name='対象職種'),
        ),
    ]
