# Generated by Django 3.2.8 on 2021-10-01 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '職種', 'verbose_name_plural': '職種'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '役職', 'verbose_name_plural': '役職'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '職員', 'verbose_name_plural': '職員'},
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=32, verbose_name='職種名'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=32, verbose_name='権限名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.job', verbose_name='職種名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.role', verbose_name='権限名'),
        ),
    ]
