# Generated by Django 3.2.8 on 2021-10-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20211001_1348'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='maker',
            field=models.ForeignKey(limit_choices_to={'job': 1}, on_delete=django.db.models.deletion.PROTECT, to='staff.staff', verbose_name='作成者'),
        ),
    ]
