# Generated by Django 3.2.8 on 2021-10-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('patient', '0002_alter_disease_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rest',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=None, max_length=64, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name_kana',
            field=models.CharField(default=None, max_length=64, verbose_name='なまえ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=None, max_length=64, verbose_name='苗字'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name_kana',
            field=models.CharField(default=None, max_length=64, verbose_name='みょうじ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('UNKNOWN', '不明'), ('male', '男性'), ('female', '女性')], default='UNKNOWN', max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.disease', verbose_name='疾患名'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.rest', verbose_name='安静度'),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
    ]
