# Generated by Django 3.2.8 on 2021-10-01 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_auto_20211001_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='疾患名')),
                ('maker', models.ForeignKey(limit_choices_to={'job': '医師'}, on_delete=django.db.models.deletion.PROTECT, to='staff.staff', verbose_name='作成者')),
            ],
            options={
                'verbose_name': '疾患',
                'verbose_name_plural': '疾患',
            },
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32, verbose_name='安静度')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff', verbose_name='作成者')),
            ],
            options={
                'verbose_name': '安静度',
                'verbose_name_plural': '安静度',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='氏名')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年齢')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.disease', verbose_name='疾患名')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.rest', verbose_name='安静度')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
            },
        ),
    ]
