# Generated by Django 3.2.8 on 2021-10-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_role_target'),
        ('staff', '0004_auto_20211008_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
